project:
  type: website

website:
  title: "Your Name - Accounting Analytics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: posts.qmd
        text: Blog
    right:
      - icon: mail
        href: mailto:youraddress@sonoma.edu
      - icon: linkedin
        href: https://linkedin.com/in/yourprofile

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true